extends: spectral:oas3
rules: 
  operation-tags: false
  operation-description: false
  valid-example-in-schemas: false
  valid-schema-example-in-content: false
  valid-schema-example-in-parameters: false
  valid-oas-example-in-content: false
  valid-oas-example-in-parameters: false
