extends: spectral:oas
functions: [nexmo-property-name-underscores]
rules:
  example-value-or-externalValue: false
  oas3-unused-components-schema: false # needed by inter-file references e.g. Voice API
  oas3-valid-content-schema-example: false
  oas3-valid-oas-content-example: false
  oas3-valid-oas-parameter-example: false
  oas3-valid-parameter-schema-example: false
  oas3-valid-schema-example: false
  openapi-tags: false
  operation-description: false
  operation-tags: false

  nexmo-property-name-underscores:
    severity: warn
    recommended: true
    given: "$.paths.*.*.parameters.*.name"
    then:
      function: "nexmo-property-name-underscores"

  nexmo-response-property-name-underscores:
    severity: warn
    recommended: true
    given: "$..components.schemas.*.properties[*]~"
    then:
      function: "nexmo-property-name-underscores"

