---
openapi: 3.0.0
info:
  version: 1.0.1
  title: Voice API BETA
  description: |
      This is the *beta* version of the Voice API. Calls created with v2 must be managed
      using [v1 endpoints](/api/voice).

      Voice v2 is provided to allow users to create IP calls. If you do not have this requirement
      we recommend that you stay on v1 for now.

      > This API may break backwards compatibility at short notice (60 days)
  contact:
    name: Nexmo DevRel
    email: devrel@nexmo.com
    url: 'https://developer.nexmo.com/'
servers:
- url: https://api.nexmo.com/v2
paths:
  "/calls":
    post:
      security:
        "$ref": "voice.yml#/paths/~1calls/post/security"
      summary: 
        "$ref": "voice.yml#/paths/~1calls/post/summary"
      description:
        "$ref": "voice.yml#/paths/~1calls/post/description"
      operationId:
        "$ref": "voice.yml#/paths/~1calls/post/operationId"
      requestBody:
        description: Call Details
        content:
          application/json:
            schema:
              required:
                - to
                - from
                - event_url
              properties:
                to:
                  type: array
                  items:
                    oneOf:
                    - "$ref": "./voice.yml#/components/schemas/EndpointPhone"
                    - "$ref": "./voice.yml#/components/schemas/EndpointApp"
                    - "$ref": "./voice.yml#/components/schemas/EndpointSip"
                    - "$ref": "./voice.yml#/components/schemas/EndpointWebsocket"
                    - "$ref": "./voice.yml#/components/schemas/EndpointVBCExtension"
                from:
                  "$ref": "voice.yml#/paths/~1calls/post/requestBody/content/application~1json/schema/properties/from"
                ncco:
                  "$ref": "voice.yml#/paths/~1calls/post/requestBody/content/application~1json/schema/properties/ncco"
                answer_url:
                  "$ref": "voice.yml#/paths/~1calls/post/requestBody/content/application~1json/schema/properties/answer_url"
                answer_method:
                  "$ref": "voice.yml#/paths/~1calls/post/requestBody/content/application~1json/schema/properties/answer_method"
                event_url:
                  "$ref": "voice.yml#/paths/~1calls/post/requestBody/content/application~1json/schema/properties/event_url"
                event_method:
                  "$ref": "voice.yml#/paths/~1calls/post/requestBody/content/application~1json/schema/properties/event_method"
                machine_detection:
                  "$ref": "voice.yml#/paths/~1calls/post/requestBody/content/application~1json/schema/properties/machine_detection"
                length_timer:
                  "$ref": "voice.yml#/paths/~1calls/post/requestBody/content/application~1json/schema/properties/length_timer"
                ringing_timer:
                  "$ref": "voice.yml#/paths/~1calls/post/requestBody/content/application~1json/schema/properties/ringing_timer"
      responses:
        '202':
          description: Accepted
          content:
            application/json:
              schema:
                type: object
                properties: {}

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
