---
openapi: 3.0.0
info:
  version: 2.2.0
  title: Voice API BETA
  description: |
    This is the *beta* version of the Voice API. Calls created with v2 must be managed
    using [v1 endpoints](/api/voice).

    Voice v2 is provided to allow users to create IP calls. If you do not have this requirement
    we recommend that you stay on v1 for now.

    > This API may break backwards compatibility at short notice (60 days)
  contact:
    name: Nexmo DevRel
    email: devrel@nexmo.com
    url: "https://developer.nexmo.com/"
servers:
  - url: https://api.nexmo.com/v2/calls
paths:
  "/":
    post:
      security:
        - bearerAuth: []
      summary:
        "$ref": "voice.yml#/paths/~1/post/summary"
      description:
        "$ref": "voice.yml#/paths/~1/post/description"
      operationId:
        "$ref": "voice.yml#/paths/~1/post/operationId"
      requestBody:
        "$ref": "#/components/requestBodies/CreateCallRequestBody"
      responses:
        "202":
          description: Accepted
          content:
            application/json:
              schema:
                type: object
                properties: {}

      callbacks:
        delivery-receipt:
          "{$request.body#/event_url}":
            post:
              summary: Call Placed Callback
              operationId: call-placed
              x-example-path: "/webhooks/event_url"
              description: Each time a leg is created you'll receive a webhook containing the leg ID (`uuid`) and the conversation ID (`conversation_uuid`) in addition to the `to` and `from` addresses.
              requestBody:
                required: true
                content:
                  application/json:
                    schema:
                      $ref: "#/components/schemas/CallPlacedWebhook"
              responses:
                "200":
                  description: Your server returns this code if it accepts the callback

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  requestBodies:
    CreateCallRequestBody:
      description: Call Details
      content:
        application/json:
          schema:
            oneOf:
              - "$ref": "voice.yml#/components/schemas/CreateCallRequestNcco"
              - "$ref": "voice.yml#/components/schemas/CreateCallRequestAnswerUrl"

  schemas:
    CallPlacedWebhook:
      properties:
        from:
          type: string
          description: The source of the call
          example: 14155550100
        to:
          type: string
          description: The destination endpoint. This can be a PSTN, SIP, IP or Websocket address
          example: 14155550105 / jamie
        uuid:
          type: string
          description: The UUID of the Conversion that the event relates to
          example: 63f61863-4a51-4f6b-86e1-46edebcf9356
        conversation_uuid:
          type: string
          description: The UUID of the call leg that the event relates to
          example: CON-f972836a-550f-45fa-956c-12a2ab5b7d22
        client_ref:
          type: string
          description: The client reference number that the event relates to. This is returned for outbound IP calls instead of a UUID.
          example: client-ref
        status:
          type: string
          example: started
        direction:
          type: string
          description: Possible values are `outbound` or `inbound`
          example: outbound
          enum:
            - outbound
            - inbound
        timestamp:
          type: string
          format: date-time
          example: 2018-01-12T15:01:55.315Z
